set(_CATKIN_CURRENT_PACKAGE "odom_printer")
set(odom_printer_VERSION "0.0.0")
set(odom_printer_MAINTAINER "isro <isro@todo.todo>")
set(odom_printer_PACKAGE_FORMAT "2")
set(odom_printer_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp")
set(odom_printer_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp")
set(odom_printer_BUILDTOOL_DEPENDS "catkin")
set(odom_printer_BUILDTOOL_EXPORT_DEPENDS )
set(odom_printer_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp")
set(odom_printer_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp")
set(odom_printer_TEST_DEPENDS )
set(odom_printer_DOC_DEPENDS )
set(odom_printer_URL_WEBSITE "")
set(odom_printer_URL_BUGTRACKER "")
set(odom_printer_URL_REPOSITORY "")
set(odom_printer_DEPRECATED "")