// Generated by gencpp from file drone_pkg/GridDetection.msg
// DO NOT EDIT!


#ifndef DRONE_PKG_MESSAGE_GRIDDETECTION_H
#define DRONE_PKG_MESSAGE_GRIDDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drone_pkg
{
template <class ContainerAllocator>
struct GridDetection_
{
  typedef GridDetection_<ContainerAllocator> Type;

  GridDetection_()
    : header()
    , row1()
    , row2()
    , row3()  {
    }
  GridDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , row1(_alloc)
    , row2(_alloc)
    , row3(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _row1_type;
  _row1_type row1;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _row2_type;
  _row2_type row2;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _row3_type;
  _row3_type row3;





  typedef boost::shared_ptr< ::drone_pkg::GridDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_pkg::GridDetection_<ContainerAllocator> const> ConstPtr;

}; // struct GridDetection_

typedef ::drone_pkg::GridDetection_<std::allocator<void> > GridDetection;

typedef boost::shared_ptr< ::drone_pkg::GridDetection > GridDetectionPtr;
typedef boost::shared_ptr< ::drone_pkg::GridDetection const> GridDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_pkg::GridDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_pkg::GridDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_pkg::GridDetection_<ContainerAllocator1> & lhs, const ::drone_pkg::GridDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.row1 == rhs.row1 &&
    lhs.row2 == rhs.row2 &&
    lhs.row3 == rhs.row3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_pkg::GridDetection_<ContainerAllocator1> & lhs, const ::drone_pkg::GridDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_pkg::GridDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_pkg::GridDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_pkg::GridDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_pkg::GridDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_pkg::GridDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_pkg::GridDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_pkg::GridDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5913507622e805e6fa0e2a5ae80a4232";
  }

  static const char* value(const ::drone_pkg::GridDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5913507622e805e6ULL;
  static const uint64_t static_value2 = 0xfa0e2a5ae80a4232ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_pkg::GridDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_pkg/GridDetection";
  }

  static const char* value(const ::drone_pkg::GridDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_pkg::GridDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32[] row1\n"
"int32[] row2\n"
"int32[] row3\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::drone_pkg::GridDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_pkg::GridDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.row1);
      stream.next(m.row2);
      stream.next(m.row3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_pkg::GridDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_pkg::GridDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "row1[]" << std::endl;
    for (size_t i = 0; i < v.row1.size(); ++i)
    {
      s << indent << "  row1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.row1[i]);
    }
    s << indent << "row2[]" << std::endl;
    for (size_t i = 0; i < v.row2.size(); ++i)
    {
      s << indent << "  row2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.row2[i]);
    }
    s << indent << "row3[]" << std::endl;
    for (size_t i = 0; i < v.row3.size(); ++i)
    {
      s << indent << "  row3[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.row3[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_PKG_MESSAGE_GRIDDETECTION_H
