#!/usr/bin/env python

import rospy

from std_msgs.msg import String
from mavros_msgs.msg import State, PositionTarget, OverrideRCIn
from mavros_msgs.srv import CommandBool, CommandTOL, SetMode
from std_srvs.srv import Empty
from geometry_msgs.msg import PoseStamped

import threading

class DroneController(object):
    def __init__(self):
        rospy.init_node('drone_controller')

        self.is_connected = False
        self.is_armed = False
        self.mode = ""

        rospy.Subscriber("/manual_drone_cmds", String, self.manual_cmd_cb)
        rospy.Subscriber("/mavros/state", State, self.state_cb) 
        rospy.Subscriber("/mavros/vision_pose/pose", PoseStamped, self.pose_cb)

        self.rc_override_pub = rospy.Publisher("/mavros/rc/override", OverrideRCIn, queue_size=10)

        self.set_ekf_origin()
        
        self.pause_odom() # Since in takeoff, odom is shit

        self.is_vision_pose_healthy = False


    def manual_cmd_cb(self, msg):
        cmd = msg.data.strip().lower()
        rospy.loginfo("[MANUAL CMD] Received: '{}'".format(cmd))
        if cmd == "arm":
            self.arm_drone()
        elif cmd == "disarm":
            self.disarm_drone()
        elif cmd.startswith("mode"):
            parts = cmd.split()
            if len(parts) == 2:
                self.set_mode(parts[1])
            else:
                rospy.logwarn("Usage: 'mode <MODE>'")
        elif cmd in ("land", "l"):
            self.land_immediately()
        elif cmd == "takeoff":
            self.takeoff()
        elif cmd == "mission":
            threading.Thread(target=self.mission).start()
        else:
            rospy.logwarn("Unknown manual command: '{}'".format(cmd))

    def state_cb(self, msg):
        self.is_connected = msg.connected
        self.is_armed = msg.armed
        self.mode = msg.mode

        rospy.loginfo("[{} | {} | {}]".format(
            "Connected" if self.is_connected else "Disconnected",
            "Armed" if self.is_armed else "Disarmed",
            self.mode
        ))

    def pose_cb(self, msg):
        pose = msg.pose
        if pose.position.x == pose.position.y == pose.position.z == 0.0000 and \
           pose.orientation.x == pose.orientation.y == pose.orientation.z == pose.orientation.w == 0.000:
            self.is_vision_pose_healthy = False
        else:
            self.is_vision_pose_healthy = True

    def set_ekf_origin(self):
        rospy.loginfo("Trying to set EKF Origin")
        rospy.wait_for_service('/mavros/global_position/set_gp_origin')
        try:
            set_origin = rospy.ServiceProxy('/mavros/global_position/set_gp_origin', SetGPOrigin)
            geo_point = GeoPoint(latitude=11.3218, longitude=75.9361, altitude=0.0)
            resp = set_origin(geo_point)
            if resp.success:
                rospy.loginfo("EKF origin set successfully.")
            else:
                rospy.logwarn("Failed to set EKF origin (service returned false).")
        except rospy.ServiceException as e:
            rospy.logerr("Service call failed: %s", e)


    def arm_drone(self):
        rospy.wait_for_service('mavros/cmd/arming')
        try:
            arming_client = rospy.ServiceProxy('mavros/cmd/arming', CommandBool)
            resp = arming_client(True)
            if resp.success:
                rospy.loginfo("Arming succeeded.")
            else:
                rospy.logerr("Arming failed. (Service call succeeded)")
        except rospy.ServiceException as e:
            rospy.logerr("Arming call failed. (err: %s)", e)

    def disarm_drone(self):
        rospy.wait_for_service('mavros/cmd/arming')
        try:
            arming_client = rospy.ServiceProxy('mavros/cmd/arming', CommandBool)
            resp = arming_client(False)
            if resp.success:
                rospy.loginfo("Disarming succeeded.")
            else:
                rospy.logerr("Disarming failed. (Service call succeeded)")
        except rospy.ServiceException as e:
            rospy.logerr("Disarming call failed. (err: %s)", e)
    

    def takeoff(self):
        msg = OverrideRCIn()
        msg.channels = [0] * 18
        self.takeoff_throttle = 1500
        self.takeoff_duration = 10

        self.takeoff_start_time = rospy.get_time()
        msg.channels[2] = self.takeoff_throttle
        self.takeoff_msg = msg

        rate = rospy.Rate(10) 
        while rospy.get_time() - self.takeoff_start_time <= self.takeoff_duration:
            self.rc_override_pub.publish(self.takeoff_msg)
            rate.sleep()

        rospy.loginfo("Takeoff completed.")

     

    def pause_odom(self):
        try:
            rospy.wait_for_service('/rtabmap/pause_odom', timeout=1)
            pause_odom_client = rospy.ServiceProxy('/rtabmap/pause_odom', Empty)
            resp = pause_odom_client()
            rospy.loginfo("Odometry paused.")
        except (rospy.ROSException, rospy.ServiceException) as e:
            rospy.logerr("Odometry pause call failed. (err: %s)", e)
            
    
    def reset_odom(self):
        try:
            rospy.wait_for_service('/rtabmap/reset_odom', timeout=1)
            reset_odom_client = rospy.ServiceProxy('/rtabmap/reset_odom', Empty)
            resp = reset_odom_client()
            rospy.loginfo("Odometry resetted.")
        except (rospy.ROSException, rospy.ServiceException) as e:
            rospy.logerr("Odometry reset call failed. (err: %s)", e)


    def resume_odom(self):
        try:
            rospy.wait_for_service('/rtabmap/resume_odom', timeout=1)
            resume_odom_client = rospy.ServiceProxy('/rtabmap/resume_odom', Empty)
            resp = resume_odom_client()
            rospy.loginfo("Odometry resumed.")
        except (rospy.ROSException, rospy.ServiceException) as e:
            rospy.logerr("Odometry resume call failed. (err: %s)", e)


    def hover_in_guided(self, hover_time=15):
        rospy.loginfo("STARTING HOVER FOR %s secs.", hover_time)
        sp_pub = rospy.Publisher("/mavros/setpoint_raw/local", PositionTarget, queue_size=10) 
        sp_msg = PositionTarget()
        sp_msg.coordinate_frame = PositionTarget.FRAME_BODY_NED
        sp_msg.type_mask = PositionTarget.IGNORE_VX | PositionTarget.IGNORE_VY | PositionTarget.IGNORE_VZ | \
                           PositionTarget.IGNORE_AFX | PositionTarget.IGNORE_AFY | PositionTarget.IGNORE_AFZ | \
                           PositionTarget.IGNORE_YAW | PositionTarget.IGNORE_YAW_RATE
        sp_msg.position.x = 0
        sp_msg.position.y = 0
        sp_msg.position.z = 0
        
        hover_start_time = rospy.get_time()

        rate = rospy.Rate(10)  # 10 Hz
        while (rospy.get_time() - hover_start_time <= hover_time): 
            sp_msg.header.stamp = rospy.Time.now()
            sp_pub.publish(sp_msg)
            rate.sleep()

        rospy.loginfo("HOVER completed.")


    def mission(self):
        """
        1. Takeoff: Pause odom. Switch to FLOW_HOLD. Pilot takeoff. Reset odom. Resume odom. 
        2. Check for vision_pose estimate to come and then switch to GUIDED. 
        3. Publish current pos. continuously to hold position.
        """

        self.mission_status = "STARTED"
        rospy.loginfo("STARTED MISSION")

        self.set_mode("22") # FLOW_HOLD
        self.pause_odom()
        self.arm_drone()
        self.takeoff()
        self.reset_odom()
        self.resume_odom()

        self.stop_mission = False

        rospy.loginfo("Waiting 5s for RTABMAP to give position estimate...")
        rospy.sleep(5)

        while not self.stop_mission:
            if self.is_vision_pose_healthy:
                if self.mode != "GUIDED":
                    self.set_mode("GUIDED")
                # to hold position
                self.hover_in_guided()
                self.set_mode("LAND")
                self.stop_mission = True
            else:
                rospy.loginfo("VISION POSE NOT HEALTHY")
                self.land_immediately()
                self.stop_mission = True
        


    def set_mode(self, mode):
        rospy.wait_for_service('mavros/set_mode')
        try:
            mode_client = rospy.ServiceProxy('/mavros/set_mode', SetMode) 
            resp = mode_client(0, mode.upper())
            if resp.mode_sent:
                rospy.loginfo("Mode set to [%s] successfully.", mode.upper())
            else:
                rospy.logerr("SetMode failed. (Service call succeeded)")

        except rospy.ServiceException as e:
            rospy.loggerr("SetMode call failed (e: %s)", e)

    def land_immediately(self):
        rospy.logwarn("LANDING NOW!")
        self.set_mode("LAND")


if __name__ == '__main__':
    node = DroneController()
    rospy.spin()
    # TODO: Add interrupts for safe landing
